global:
    scrape_interval: 2s
    evaluation_interval: 2s

alerting:

rule_files:

scrape_configs:
- job_name: "prometheus"
  static_configs:
  - targets: ["prometheus:9090"]

- job_name: "queue_configurator"
  static_configs:
  - targets: ["queue_configurator:40200"]

- job_name: "vehicle_entry"
  static_configs:
  - targets: ["vehicle_entry:41000"]

- job_name: "vehicle_exit"
  static_configs:
  - targets: ["vehicle_exit:42000"]

- job_name: "go_backend"
  static_configs:
  - targets: ["go_backend:43000"]

- job_name: "web_backend"
  static_configs:
  - targets: ["web_backend:40100"]
