{
 "title": "Go Backend",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Vehicle Entry Event Processing Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_backend_event_processing_delay{event_type=\"entry_event\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicle Entry Event Processing Delay (Histogram)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_backend_event_processing_delay{event_type=\"entry_event\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicle Exit Event Processing Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_backend_event_processing_delay{event_type=\"exit_event\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicle Exit Event Processing Delay (Histogram)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_backend_event_processing_delay{event_type=\"exit_event\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicle Entry Events Processed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_backend_total_processed_events{event_type=\"entry_event\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicle Exit Events Processed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_backend_total_processed_events{event_type=\"exit_event\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entry Event 95th Percentile of Processing Delays Over 5 Minutes",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, event_type) (rate(go_backend_event_processing_delay_hist_bucket{event_type=\"entry_event\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exit Event 95th Percentile of Processing Delays Over 5 Minutes",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, event_type) (rate(go_backend_event_processing_delay_hist_bucket{event_type=\"exit_event\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicle Entry Event Average Processing Delay Over 5 Minutes",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(go_backend_event_processing_delay_hist_sum{event_type=\"entry_event\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicle Exit Event Average Processing Delay Over 5 Minutes",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(go_backend_event_processing_delay_hist_sum{event_type=\"exit_event\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Backend Startup Delay",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_backend_startup_delay", "legendFormat": "__auto" }
   ]
  }
 ]
}