{
 "title": "Vehicle Exit",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Vehicle Exit Event Processing Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vehicle_exit_event_processing_delay",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicle Exit Event Processing Delay (Histogram)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vehicle_exit_event_processing_delay",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicle Exit Events Processed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vehicle_exit_total_processed_events",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicle Exit Service Startup Delay",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vehicle_exit_startup_delay", "legendFormat": "__auto" }
   ]
  }
 ]
}