{
 "title": "Web Backend",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Web Backend HTTP POST Request Processing Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "web_backend_http_request_duration_seconds{method=\"POST\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web Backend HTTP POST Request Processing Delay (Histogram)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "web_backend_http_request_duration_seconds{method=\"POST\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web Backend HTTP POST Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "web_backend_http_requests_count_total{method=\"POST\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web Backend HTTP GET Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "web_backend_http_requests_count_total{method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web Backend HTTP GET Request Processing Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "web_backend_http_request_duration_seconds{method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web Backend HTTP GET Request Processing Delay (Histogram)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "web_backend_http_request_duration_seconds{method=\"GET\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}